spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8762
renderer:
  services:
  - renderer-xsl
  - renderer-docx
zuul:
  routes:
    render:
      path: /render